config/routes.rb
Rails.application.routes.draw do

  get 'orders/details'

  get 'books/aboutus', :as => :aboutus

  get 'orders/show', :as => :orders

  get "cart" => "cart#show"
  get "cart/add/:id" => "cart#add", :as => :add_to_cart
  post "cart/remove/:id" => "cart#remove", :as => :remove_from_cart
  post "cart/checkout" => "cart#checkout", :as => :checkout
  post "cart/update/:id" => "cart#update", :as => :line_items_update

  devise_for :users, controllers: {registrations: "registrations"}
  resources :books

  root to: 'books#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/about_u.rb
class AboutU < ApplicationRecord
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :authorBooks

  def full_name
    first_name + " " + last_name
  end
end

app/models/author_book.rb
class AuthorBook < ApplicationRecord
  belongs_to :author
  belongs_to :book
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :type
  belongs_to :status
  has_many :authorBooks
  has_many :custReviews
  has_many :lineItems

  validates :name, presence: true
  validates :quantity_in_stock, numericality: { only_integer: true, greater_than_or_equal_to: 0}, :allow_nil => false
  validates :pur_in_price, numericality: {greater_than_or_equal_to: 0.1}, :allow_nil => false
  validates :sell_price, numericality: {greater_than_or_equal_to: 0.1}, :allow_nil => false

  mount_uploader :image, ImageUploader


  scope :search_by_name, lambda {|query|where(['"books"."name" LIKE ?', "%#{query}%"])}
  scope :search_by_type, lambda {|query|where(['"types"."name" LIKE ?', "%#{query}%"])}
  scope :search_by_status, lambda {|query|where(['"statuses"."name" LIKE ?', "%#{query}%"])}
end

app/models/cust_review.rb
class CustReview < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order
  belongs_to :book

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :province
  belongs_to :orderstatus
  has_many :lineItems

  scope :in_progress, ->{ where("orders.orderstatus_id = 1") }
  scope :placed, -> { where("orders.orderstatus_id = 2") }
  scope :shipped, -> { where("orders.orderstatus_id = 3") }
  scope :cancelled, -> { where("orders.orderstatus_id = 4") }
  scope :completed, -> { where("orders.orderstatus_id = 5") }

  def checkout!
    self.checked_out_at = Time.zone.now
    self.save
    self.lineItems.each do |item|
      bookSold = item.book
      bookSold.quantity_in_stock -= item.quantity
      bookSold.save
    end
  end

  def recalculate_price!(id)
    self.sub_total = lineItems.inject(0.0){ |sum, lineItem| sum += lineItem.price * lineItem.quantity * (1-lineItem.book.status.des_percentage) }
    self.gst = self.sub_total * User.find(id).province.GST
    self.pst = self.sub_total * User.find(id).province.PST
    self.hst = self.sub_total * User.find(id).province.HST
    self.total_price = self.sub_total + self.gst + self.pst + self.hst
    if self.orderstatus_id.nil?
      self.orderstatus_id = 1
    end
    save!
  end

  def display_name
    ActionController::Base.helpers.number_to_currency(total_price) +
        " - Order ##{id} (#{user.first_name})"
  end
end

app/models/orderstatus.rb
class Orderstatus < ApplicationRecord
  has_many :orders
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :users
  has_many :orders
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :books
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :books
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders, :dependent => :destroy
  belongs_to :province
  validates :email, presence: true
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :getType

  def index
    @statuses = Status.all

    @selected_type = params[:type]
    @selected_status = params[:status]


    @books = Book.joins(:type, :status).search_by_name(params[:search]).search_by_type(params[:type])
      .search_by_status(params[:status]).page(params[:page]).per(3)

  end

  def show
    @book = Book.find(params[:id])
  end

  def aboutus
    @about = AboutU.last
  end

  def getType
    @types = Type.all
  end

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_filter :find_cart
  before_action :authenticate_user!

  def add
    @cart.save if @cart.new_record?
    session[:cart_id] = @cart.id
    book = Book.find(params[:id])
    LineItem.create! :order => @cart, :book => book, :price => book.sell_price, :quantity => 1
    @cart.recalculate_price!(current_user.id)
    flash[:notice] = "Item added to cart!"
    @description = 'Description of Charge'
    redirect_to '/cart'
  end

  def remove
    item = @cart.lineItems.find(params[:id])
    item.destroy
    @cart.recalculate_price!(current_user.id)
    flash[:notice] = "Item removed from cart"
    redirect_to '/cart'
  end

  def checkout
    amount = (@cart.total_price * 100).to_i # $5 in cents

    @customer = Stripe::Customer.create(email:  params[:stripeEmail],
                                       source: params[:stripeToken])

    @charge = Stripe::Charge.create(customer:    @customer.id,
                                    amount:      amount,
                                    description: 'Rails Stripe customer',
                                    currency:    'cad')



    if @charge.paid && @charge.amount == amount
      orderstatus = Orderstatus.where("name = 'Placed'").first
      @cart.orderstatus_id = orderstatus.id
      @cart.stripe_charge_id = @charge.id
    end

    @cart.checkout!
    session.delete(:cart_id)
    flash[:notice] = "Thank you for your purchase! We will ship it shortly!"
    redirect_to root_path
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to '/cart'
  end

  def update
    item = @cart.lineItems.find(params[:id])
    @st = params[:id]
    book_inStore = item.book.quantity_in_stock
    item.quantity = (params[:line_item][@st]).to_i>book_inStore ? book_inStore : params[:line_item][@st]#added this line here
    item.save
    @cart.recalculate_price!(current_user.id)
    flash[:notice] = "Item updated!"
    redirect_to '/cart'
  end

  protected

  def find_cart
    @cart = session[:cart_id] ? Order.find(session[:cart_id]) : current_user.orders.build
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @amount = 500 # $5 in cents
    @description = 'Description of Charge'
  end

  def create
    amount = 500 # $5 in cents

    @customer = Stripe::Customer.create(email:  params[:stripeEmail],
                                       source: params[:stripeToken])

    @charge = Stripe::Charge.create(customer:    @customer.id,
                                    amount:      amount,
                                    description: 'Rails Stripe customer',
                                    currency:    'cad')
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def show
    @orders = current_user.orders.where('orderstatus_id>1')
  end

  def details
    @order = Order.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/books/_book.html.slim
  .col-sm-4.col-lg-4.col-md-4
    .thumbnail
      = link_to image_tag(book.image_url(:thumb)), book
      .caption
        h4.pull-right =number_to_currency book.sell_price*(1-book.status.des_percentage)
        h4
          = link_to book.name[0..15].gsub(/\s\w+\s*$/, '...'), book
        p
          = book.description[0..50]
        .ratings
          p.pull-right 15 reviews
          p
              span.glyphicon.glyphicon-star
              span.glyphicon.glyphicon-star
              span.glyphicon.glyphicon-star
              span.glyphicon.glyphicon-star
              span.glyphicon.glyphicon-star

app/views/books/_side.html.slim

  .col-md-3
    p.lead Fantastic Knowledge
    .list-group
      - @types.each do |type|
        =link_to type.name, books_path(search: "", type: type.name, status: ""), class: "list-group-item"

app/views/books/aboutus.html.slim
doctype html
html
  head
      h1 About US

      #about_us
        p 
          strong Who We Are:
          = @about.whorwe
        p
          strong What We Sell:
          = @about.whatwesell
        p
          strong What We Want:
          = @about.whatwewant
      div style="clear:both;" 

app/views/books/index.html.slim
.row
  = render partial: 'side'
  .col-md-9
    .row.carousel-holder
      .col-md-12
        #carousel-example-generic.carousel.slide data-ride="carousel" 
          ol.carousel-indicators
            li data-slide-to="0" data-target="#carousel-example-generic" 
            li.active data-slide-to="1" data-target="#carousel-example-generic" 
            li data-slide-to="2" data-target="#carousel-example-generic" 
          .carousel-inner
            .item
              img.slide-image alt="" src="https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQZY8mYNb_r07yJQnCEj2EM7PGigqQTmjHrqRUUJaiSKDydvo9Q" /
            .item.active
              img.slide-image alt="" src="https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTgJcq2_wLQ9AfwGAJnUCvEw_flaagjSGl_TtPpNRPILVL_wCvm" /
            .item
              img.slide-image alt="" src="https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRkp6rye5OSyLY_cE_2CKyMuOw41G00X5lOWmvPQLz0vHeRWb39oQ" /
          a.left.carousel-control data-slide="prev" href="#carousel-example-generic" 
            span.glyphicon.glyphicon-chevron-left
          a.right.carousel-control data-slide="next" href="#carousel-example-generic" 
            span.glyphicon.glyphicon-chevron-right
    .row
      = form_tag books_path, :method => 'get' do
        p
          = text_field_tag :search, params[:search]
          = select_tag :type,  options_from_collection_for_select(@types, "name", "name", @selected_type), :include_blank => true
          = select_tag :status,  options_from_collection_for_select(@statuses, "name", "name", @selected_status), :include_blank => true
          = submit_tag "Search", :name => nil
      = render partial: 'book', collection: @books
    
      = paginate @books

app/views/books/show.html.slim
.row
  = render partial: 'side'
  .col-md-9
    .thumbnail
      img.img-responsive alt="" src="http://placehold.it/800x300" /
      .caption-full
        h4.pull-right = number_to_currency @book.sell_price * (1-@book.status.des_percentage)
        h4
          = @book.name
        p
          = @book.description
      .ratings
        p.pull-right 3 reviews
        p
          span.glyphicon.glyphicon-star
          span.glyphicon.glyphicon-star
          span.glyphicon.glyphicon-star
          span.glyphicon.glyphicon-star
          span.glyphicon.glyphicon-star-empty
          | 4.0 stars
    .well
      .text-right
        =link_to "Add to Card", add_to_cart_path(@book.id), class: "btn btn-success"
        a.btn.btn-success Leave a Review
      hr/
      .row
        .col-md-12
          span.glyphicon.glyphicon-star
          span.glyphicon.glyphicon-star
          span.glyphicon.glyphicon-star
          span.glyphicon.glyphicon-star
          span.glyphicon.glyphicon-star-empty
          | Anonymous
          span.pull-right 10 days ago
          p This product was great in terms of quality. I would definitely buy another!
      hr/
      .row
        .col-md-12
          span.glyphicon.glyphicon-star
          span.glyphicon.glyphicon-star
          span.glyphicon.glyphicon-star
          span.glyphicon.glyphicon-star
          span.glyphicon.glyphicon-star-empty
          | Anonymous
          span.pull-right 12 days ago
          p I've alredy ordered another one!
      hr/
      .row
        .col-md-12
          span.glyphicon.glyphicon-star
          span.glyphicon.glyphicon-star
          span.glyphicon.glyphicon-star
          span.glyphicon.glyphicon-star
          span.glyphicon.glyphicon-star-empty
          | Anonymous
          span.pull-right 15 days ago
          p I've seen some better than this, but not at this price. I definitely recommend this item.

app/views/orders/_list.html.slim
.orders

  h2 = order.name
  p
    strong Price:
    = number_to_currency order.price
  - if full_details
    p = order.description
    - if order.image.present?
      = image_tag order.image.url
  - else
    p = link_to 'details', order

app/views/orders/details.html.slim
h4 
  |Orders# 
  =@order.id

  table#order
    thead
      tr
        th Image
        th Items
        th Quantity
        th Price
    tbody
      - @order.lineItems.each do |item|
        tr
          td = link_to image_tag(item.book.image_url(:small)), book_path(item.book)
          td = link_to item.book.name, book_path(item.book)
          td = item.quantity
          td = number_to_currency item.price

app/views/orders/show.html.slim
h1 All Orders Placed

table#orders
  thead
    tr
      th Orders
      th Total
      th Categorys
      th Status
  tbody
    - @orders.each do |order|
      tr
        td = link_to order.id,  :action=>'details', id: order.id
        td = number_to_currency order.total_price
        td = order.lineItems.count
        td = Orderstatus.find(order.orderstatus_id).name